export const AuditEvents = {
  VP_TEMPLATE_ISSUED: 'VP_TEMPLATE_ISSUED',
  VP_VERIFIED: 'VP_VERIFIED',
  VP_REJECTED: 'VP_REJECTED',
  ENROLLMENT_TOKEN_GENERATED: 'ENROLLMENT_TOKEN_GENERATED',
  ENROLLMENT_TOKEN_CONSUMED: 'ENROLLMENT_TOKEN_CONSUMED',
  ENROLLMENT_TOKEN_REJECTED: 'ENROLLMENT_TOKEN_REJECTED',
  CHALLENGE_ISSUED: 'CHALLENGE_ISSUED',
  CHALLENGE_VERIFIED: 'CHALLENGE_VERIFIED',
  CHALLENGE_REJECTED: 'CHALLENGE_REJECTED',
  AGENT_ONBOARDED: 'AGENT_ONBOARDED',
  USER_DID_VERIFIED: 'USER_DID_VERIFIED'
} as const;

export type AuditEvent = (typeof AuditEvents)[keyof typeof AuditEvents];
