export const AuditEvents = {
  // B1 — DID & Hedera
  DID_CREATED: 'DID_CREATED',
  DID_CREATION_FAILED: 'DID_CREATION_FAILED',
  DID_RESOLVED: 'DID_RESOLVED',
  DID_UPDATED: 'DID_UPDATED',
  DID_UPDATE_FAILED: 'DID_UPDATE_FAILED',
  DID_DEACTIVATED: 'DID_DEACTIVATED',

  // B2 — VC Issuance & Management
  VC_ISSUED: 'VC_ISSUED',
  VC_ISSUANCE_FAILED: 'VC_ISSUANCE_FAILED',
  VC_REVOKED: 'VC_REVOKED',
  VC_REVOCATION_FAILED: 'VC_REVOCATION_FAILED',
  VC_RENEWED: 'VC_RENEWED',
  VC_RENEWAL_FAILED: 'VC_RENEWAL_FAILED',
  VC_STATUS_CHECKED: 'VC_STATUS_CHECKED',
  STATUS_LIST_UPDATED: 'STATUS_LIST_UPDATED',

  // B3 — VP
  VP_TEMPLATE_ISSUED: 'VP_TEMPLATE_ISSUED',
  VP_VERIFIED: 'VP_VERIFIED',
  VP_REJECTED: 'VP_REJECTED',

  // B4 — Agent & User
  ENROLLMENT_TOKEN_GENERATED: 'ENROLLMENT_TOKEN_GENERATED',
  ENROLLMENT_TOKEN_CONSUMED: 'ENROLLMENT_TOKEN_CONSUMED',
  ENROLLMENT_TOKEN_REJECTED: 'ENROLLMENT_TOKEN_REJECTED',
  CHALLENGE_ISSUED: 'CHALLENGE_ISSUED',
  CHALLENGE_VERIFIED: 'CHALLENGE_VERIFIED',
  CHALLENGE_REJECTED: 'CHALLENGE_REJECTED',
  AGENT_ONBOARDED: 'AGENT_ONBOARDED',
  USER_DID_VERIFIED: 'USER_DID_VERIFIED',
} as const;

export type AuditEventType = (typeof AuditEvents)[keyof typeof AuditEvents];
export type AuditEvent = {
  event: AuditEventType;
  timestamp: string;
  requestId: string;
  [key: string]: unknown;
};
