export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ADMIN_AUTH_REQUIRED: 'ADMIN_AUTH_REQUIRED',

  // B1 — DID & Hedera
  INVALID_PUBLIC_KEY: 'INVALID_PUBLIC_KEY',
  INVALID_DID_FORMAT: 'INVALID_DID_FORMAT',
  DID_NOT_FOUND: 'DID_NOT_FOUND',
  DID_ALREADY_EXISTS: 'DID_ALREADY_EXISTS',
  DID_DEACTIVATED: 'DID_DEACTIVATED',
  INVALID_SERVICE_ENDPOINT_URL: 'INVALID_SERVICE_ENDPOINT_URL',
  SERVICE_ENDPOINT_NOT_FOUND: 'SERVICE_ENDPOINT_NOT_FOUND',
  SERVICE_ENDPOINT_ALREADY_EXISTS: 'SERVICE_ENDPOINT_ALREADY_EXISTS',
  HEDERA_ANCHOR_FAILED: 'HEDERA_ANCHOR_FAILED',
  HEDERA_RESOLUTION_FAILED: 'HEDERA_RESOLUTION_FAILED',

  // B2 — VC Issuance & Management
  VC_NOT_FOUND: 'VC_NOT_FOUND',
  VC_ALREADY_REVOKED: 'VC_ALREADY_REVOKED',
  VC_EXPIRED: 'VC_EXPIRED',
  VC_SUBJECT_DID_NOT_FOUND: 'VC_SUBJECT_DID_NOT_FOUND',
  VC_INVALID_PRIVILEGE_SCOPE: 'VC_INVALID_PRIVILEGE_SCOPE',
  STATUS_LIST_INDEX_EXHAUSTED: 'STATUS_LIST_INDEX_EXHAUSTED',
  STATUS_LIST_NOT_FOUND: 'STATUS_LIST_NOT_FOUND',
  VC_SIGNATURE_INVALID: 'VC_SIGNATURE_INVALID',
  VC_REVOKED: 'VC_REVOKED',
  VC_ISSUER_NOT_FOUND: 'VC_ISSUER_NOT_FOUND',
  DELEGATION_NOT_PERMITTED: 'DELEGATION_NOT_PERMITTED',
  DELEGATION_DEPTH_EXCEEDED: 'DELEGATION_DEPTH_EXCEEDED',
  DELEGATION_SCOPE_ESCALATION: 'DELEGATION_SCOPE_ESCALATION',
  DELEGATION_CHAIN_INVALID: 'DELEGATION_CHAIN_INVALID',
  DELEGATION_PARENT_VC_NOT_FOUND: 'DELEGATION_PARENT_VC_NOT_FOUND',
  DELEGATION_PARENT_VC_REVOKED: 'DELEGATION_PARENT_VC_REVOKED',

  // B3 — VP
  VP_NOT_FOUND: 'VP_NOT_FOUND',
  VP_EXPIRED: 'VP_EXPIRED',
  VP_ALREADY_CONSUMED: 'VP_ALREADY_CONSUMED',
  VP_VERIFICATION_FAILED: 'VP_VERIFICATION_FAILED',
  VP_INVALID_STRUCTURE: 'VP_INVALID_STRUCTURE',
  VP_AGENT_DID_NOT_FOUND: 'VP_AGENT_DID_NOT_FOUND',
  VP_NO_ACTIVE_VC: 'VP_NO_ACTIVE_VC',
  VP_MULTIPLE_ACTIVE_VC: 'VP_MULTIPLE_ACTIVE_VC',
  JWT_INVALID: 'JWT_INVALID',
  JWT_EXPIRED: 'JWT_EXPIRED',
  JWT_PUBLIC_KEY_NOT_FOUND: 'JWT_PUBLIC_KEY_NOT_FOUND',

  // B4 — Agent & User
  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
  SERVICE_ALREADY_EXISTS: 'SERVICE_ALREADY_EXISTS',
  ENROLLMENT_TOKEN_NOT_FOUND: 'ENROLLMENT_TOKEN_NOT_FOUND',
  ENROLLMENT_TOKEN_EXPIRED: 'ENROLLMENT_TOKEN_EXPIRED',
  ENROLLMENT_TOKEN_ALREADY_USED: 'ENROLLMENT_TOKEN_ALREADY_USED',
  CHALLENGE_NOT_FOUND: 'CHALLENGE_NOT_FOUND',
  CHALLENGE_EXPIRED: 'CHALLENGE_EXPIRED',
  CHALLENGE_ALREADY_VERIFIED: 'CHALLENGE_ALREADY_VERIFIED',
  CHALLENGE_SIGNATURE_INVALID: 'CHALLENGE_SIGNATURE_INVALID',
  AGENT_ALREADY_ONBOARDED: 'AGENT_ALREADY_ONBOARDED',
} as const;

export const ErrorCode = ErrorCodes;
export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
