export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PUBLIC_KEY: 'INVALID_PUBLIC_KEY',
  INVALID_SERVICE_ENDPOINT_URL: 'INVALID_SERVICE_ENDPOINT_URL',
  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
  SERVICE_ALREADY_EXISTS: 'SERVICE_ALREADY_EXISTS',
  ENROLLMENT_TOKEN_NOT_FOUND: 'ENROLLMENT_TOKEN_NOT_FOUND',
  ENROLLMENT_TOKEN_EXPIRED: 'ENROLLMENT_TOKEN_EXPIRED',
  ENROLLMENT_TOKEN_ALREADY_USED: 'ENROLLMENT_TOKEN_ALREADY_USED',
  CHALLENGE_NOT_FOUND: 'CHALLENGE_NOT_FOUND',
  CHALLENGE_EXPIRED: 'CHALLENGE_EXPIRED',
  CHALLENGE_ALREADY_VERIFIED: 'CHALLENGE_ALREADY_VERIFIED',
  CHALLENGE_SIGNATURE_INVALID: 'CHALLENGE_SIGNATURE_INVALID',
  AGENT_ALREADY_ONBOARDED: 'AGENT_ALREADY_ONBOARDED',
  VP_NOT_FOUND: 'VP_NOT_FOUND',
  VP_EXPIRED: 'VP_EXPIRED',
  VP_ALREADY_CONSUMED: 'VP_ALREADY_CONSUMED',
  VP_VERIFICATION_FAILED: 'VP_VERIFICATION_FAILED',
  VP_INVALID_STRUCTURE: 'VP_INVALID_STRUCTURE',
  VP_AGENT_DID_NOT_FOUND: 'VP_AGENT_DID_NOT_FOUND',
  VP_NO_ACTIVE_VC: 'VP_NO_ACTIVE_VC',
  VP_MULTIPLE_ACTIVE_VC: 'VP_MULTIPLE_ACTIVE_VC',
  VC_SIGNATURE_INVALID: 'VC_SIGNATURE_INVALID',
  VC_EXPIRED: 'VC_EXPIRED',
  VC_REVOKED: 'VC_REVOKED',
  VC_ISSUER_NOT_FOUND: 'VC_ISSUER_NOT_FOUND'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
