export {
  attachHelixVP,
  encodeBase64UrlJson,
  helixidMCPMiddleware,
  type MCPError,
  type MCPMiddleware,
  type MCPMiddlewareOptions,
  type MCPMiddlewareResult,
  type MCPNext,
  type MCPRequestLike,
  type MCPToolCall,
  type VerifiedHelixContext,
  type VPAttachOptions,
  type WalletLoader,
} from './middleware.js';
