export function agentPageHtml(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Travel Planner — HelixID consent demo</title>
<style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#0f1216;color:#e8eaed;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;display:grid;place-items:center}.shell{width:min(760px,94vw);height:min(820px,94vh);background:#171b21;border:1px solid #262c36;border-radius:18px;box-shadow:0 18px 60px #0008;display:flex;flex-direction:column;overflow:hidden}.head{padding:18px 22px;border-bottom:1px solid #262c36;display:flex;align-items:center;gap:12px}.logo{width:38px;height:38px;border-radius:12px;background:linear-gradient(135deg,#1f6feb,#8957e5);display:grid;place-items:center;font-weight:800}.head h1{font-size:16px;margin:0}.head p{font-size:12px;color:#9aa4b2;margin:3px 0 0}.status{margin-left:auto;font-size:11px;color:#56d364}.log{flex:1;overflow:auto;padding:22px;display:flex;flex-direction:column;gap:12px}.msg{max-width:86%;padding:11px 14px;border-radius:13px;line-height:1.45;font-size:14px;white-space:pre-wrap}.bot{align-self:flex-start;background:#21262d;border:1px solid #30363d}.user{align-self:flex-end;background:#1f6feb22;border:1px solid #1f6feb66}.meta{align-self:center;color:#8b949e;font-size:12px}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.actions button,.primary{border:0;border-radius:9px;background:#1f6feb;color:white;padding:9px 12px;font-weight:650;cursor:pointer}.card{margin-top:10px;border:1px solid #3a414c;border-radius:11px;padding:12px;background:#15191f}.card strong{display:block;margin-bottom:5px}.card small{color:#9aa4b2}.composer{padding:14px 18px;border-top:1px solid #262c36;display:flex;gap:9px}.composer input,.login input{flex:1;background:#0f1216;color:#e8eaed;border:1px solid #30363d;border-radius:10px;padding:12px;font:inherit}.composer button{border:0;border-radius:10px;background:#1f6feb;color:#fff;padding:0 18px;font-weight:700}.login-wrap{position:fixed;inset:0;background:#0f1216;display:grid;place-items:center;z-index:5}.login{width:min(390px,90vw);background:#171b21;border:1px solid #30363d;border-radius:16px;padding:26px}.login h2{margin:0 0 6px}.login p{margin:0 0 18px;color:#9aa4b2;font-size:13px}.login input{display:block;width:100%;margin:9px 0}.login button{width:100%;margin-top:8px;padding:11px}.error{color:#ff7b72;font-size:12px}.hidden{display:none!important}
</style></head><body>
<div class="login-wrap" id="loginWrap"><form class="login" id="login"><h2>Travel Planner</h2><p>Sign in to your demo agent</p><input id="username" value="traveler" autocomplete="username" aria-label="Username"><input id="password" value="demo123" type="password" autocomplete="current-password" aria-label="Password"><button class="primary">Sign in</button><div class="error" id="loginError"></div></form></div>
<main class="shell"><header class="head"><div class="logo">H</div><div><h1>Travel Planner Agent</h1><p id="identity">HelixID consent demo</p></div><span class="status" id="plannerStatus">● Connecting</span></header><div class="log" id="log"></div><form class="composer" id="chat"><input id="message" autocomplete="off" placeholder="Ask for a flight or hotel…"><button>Send</button></form></main>
<script>
const log=document.querySelector('#log'),input=document.querySelector('#message');let pending=null,lastFlight=null,lastHotel=null,itinerary=null;
function add(kind,text,extra=''){const el=document.createElement('div');el.className='msg '+kind;el.textContent=text;if(extra)el.insertAdjacentHTML('beforeend',extra);log.append(el);log.scrollTop=log.scrollHeight;return el}
function actions(items){return '<div class="actions">'+items.map(x=>'<button type="button" data-action="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>'}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=r.status===204?{}:await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data}
async function tool(sp,tool,args,authorizationSource){return api('/api/call',{sp,tool,args,...(authorizationSource?{authorizationSource}:{})})}
function consentCard(result,call){pending={...call,consentUrl:result.consentUrl};add('bot','To continue, sign in to '+(result.sp==='airline'?'Helix Air':'Helix Stay')+' and give the agent permission.',actions([['consent','Login & authorize']]));}
function showPlanner(planner){const el=document.querySelector('#plannerStatus');if(!planner)return;el.textContent=planner.provider==='deterministic'?'● Scripted fallback':'● '+planner.provider+' · '+planner.model;el.style.color=planner.provider==='deterministic'?'#d29922':'#56d364'}
function flightResults(data,returnTrip=false){const flights=data.flights||[],query=data.query||{};lastFlight=flights[0]||null;if(!flights.length){add('bot','No Helix Air flights are available from '+(query.origin||'that origin')+' to '+(query.destination||'that destination')+(query.departureDate?' on '+query.departureDate:'')+'. Try another route or date.');return}if(!returnTrip&&lastFlight)itinerary={origin:lastFlight.origin,destination:lastFlight.destination,departureDate:lastFlight.departureDate};add('bot',(returnTrip?'I found these return flights':'I found these flights')+' from '+lastFlight.origin+' to '+lastFlight.destination+' on '+lastFlight.departureDate+':\\n\\n'+flights.map((f,i)=>(i+1)+'. '+f.flightId+' · '+f.departs+' · '+f.carrier).join('\\n'),actions([['book-flight','Book option 1']]));}
function hotelResults(data){const hotels=data.hotels||[];lastHotel=hotels[0]||null;if(!hotels.length){add('bot','No hotels are available for that search.');return}add('bot','Here are hotels in '+lastHotel.city+':\\n\\n'+hotels.map((h,i)=>(i+1)+'. '+h.name+' · ₹'+h.nightlyRate+'/night').join('\\n'),actions([['book-hotel','Book option 1']]));}
async function runCall(call){const result=await tool(call.sp,call.tool,call.args,call.authorizationSource);if(result.status==='consent_required'){consentCard(result,call);return}if(result.status!=='ok')throw new Error(result.error?.message||'Call failed');if(call.tool==='search_flights')flightResults(result.data,call.args.origin==='DEL');else if(call.tool==='search_hotels')hotelResults(result.data);else {const id=result.data.bookingId;const authCopy=result.authorizationSource==='standing_grant'?'reused your existing standing permission—no login or consent was needed.':'used the permission you just granted.';add('bot',(call.sp==='airline'?'Your flight is confirmed.':'Your hotel is confirmed.')+' The agent '+authCopy,'<div class="card"><strong>'+(call.sp==='airline'?'PNR ':'Confirmation ')+id+'</strong><small>'+result.data.status+'</small></div>');}}
async function handle(text){add('user',text);const wait=add('meta','Travel Planner is thinking…');try{const plan=await api('/api/plan',{message:text,context:{...(lastFlight?{selectedFlight:{flightId:lastFlight.flightId,origin:lastFlight.origin,destination:lastFlight.destination}}:{}),...(lastHotel?{selectedHotel:{hotelId:lastHotel.hotelId,city:lastHotel.city}}:{}),...(itinerary?{itinerary}:{})}});if(plan.kind==='message'){add('bot',plan.message);return}const sp=plan.tool==='search_hotels'||plan.tool==='book_hotel'?'hotel':'airline';if(plan.tool==='book_flight')lastFlight=null;if(plan.tool==='book_hotel')lastHotel=null;await runCall({sp,tool:plan.tool,args:plan.args})}catch(e){add('bot','I could not complete that: '+e.message)}finally{wait.remove()}}
document.querySelector('#login').onsubmit=async e=>{e.preventDefault();try{const s=await api('/api/login',{username:username.value,password:password.value});window.agentDid=s.agentDid;window.userDid=s.userDid;showPlanner(s.planner);document.querySelector('#loginWrap').classList.add('hidden');document.querySelector('#identity').textContent=s.username+' · '+s.userDid;add('bot','Hi! I can help arrange your trip. Include a travel date, for example “Find a flight from TVM to Delhi on 2026-08-15.”');input.focus()}catch(e){loginError.textContent=e.message}};
document.querySelector('#chat').onsubmit=e=>{e.preventDefault();const v=input.value.trim();if(v){input.value='';handle(v)}};
log.onclick=e=>{const a=e.target.dataset.action;if(a==='book-flight')handle('Yes, book option 1');if(a==='book-hotel')handle('Yes, book option 1');if(a==='consent'&&pending)window.open(pending.consentUrl,'helixid-consent','popup,width=520,height=720');};
window.addEventListener('message',async e=>{if(!['http://localhost:4101','http://localhost:4102'].includes(e.origin))return;if(e.data?.type==='helixid:consent-accepted'&&pending){try{await api('/api/grants',{grantVC:e.data.grantVC});const call={...pending,authorizationSource:'fresh_consent'};pending=null;await runCall(call)}catch(err){add('bot','Could not store the permission: '+err.message)}}if(e.data?.type==='helixid:consent-declined'){pending=null;add('bot','Permission was declined, so I did not make the booking.')}});
(async()=>{const s=await api('/api/session');showPlanner(s.planner);if(s.authenticated){loginWrap.classList.add('hidden');window.agentDid=s.agentDid;window.userDid=s.userDid;identity.textContent=s.username+' · '+s.userDid;add('bot','Welcome back! Ask me for a dated flight search.')}})();
</script></body></html>`;
}
